### ISSUE TITLE
Move build to GitHub actions

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlQueryStress#167]
```yml
version: 0.9.7.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2022
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    dotnet restore ./src/SqlQueryStress/SqlQueryStress.csproj

    dotnet restore ./src/SqlQueryStressCLI/sqlstresscmd.csproj


    dotnet build ./src/SqlQueryStress.sln


    dotnet publish ./src/SQLQueryStress/SqlQueryStress.csproj --configuration Release --output %APPVEYOR_BUILD_FOLDER%\src\SQLQueryStress\bin\Publish\net6.0-windows\ --self-contained true


    7z a SqlQueryStressNet6.zip %APPVEYOR_BUILD_FOLDER%\src\SQLQueryStress\bin\Publish\net6.0-windows\*.exe
artifacts:
- path: SqlQueryStressNet6.zip
  name: SqlQueryStress
- path: '**\*.nupkg'
  name: sqlstresscmd
deploy:
- provider: NuGet
  api_key:
  artifact: sqlstresscmd
  on:
    branch: master

```
